### PR TITLE
Notes finalized

### PR DESCRIPTION
**Pull request by terrytay**

### CODE REVIEW

**Comment by GanapathySanathBalaji** [comment]
Can you rectify the following things too:
1) Support both 'y' and 'Y' when deleting notes
2) Don't exit notes mode when an exception is encountered

**Comment by GanapathySanathBalaji** [comment]
Maybe just merge them now, I will rectify the above issues later

**Comment by terrytay** [comment]
> Can you rectify the following things too:
> 
>     1. Support both 'y' and 'Y' when deleting notes
> 
>     2. DOn't exit notes mode when an exception is encountered

1. reason for big Y is for sensitivity.
2. fixed

**Comment by terrytay** [comment]
> Can you rectify the following things too:
> 
>     1. Support both 'y' and 'Y' when deleting notes
> 
>     2. Don't exit notes mode when an exception is encountered

change to small y if u think it's better. im done with my notes alr. i will do my notes ug by tmr lecture time!

thank you

**Comment by GanapathySanathBalaji** [comment]
OK

**Comment by NizarMohd** [comment]
Noted on the changes

**Pull request merged**
