### PR TITLE
Refactored Parser and Command Classes

### LINKED ISSUE #39: Create the Command abstract class

### LINKED ISSUE #40: Create the Parser class

### PR DESCRIPTION
**Pull request by GanapathySanathBalaji**

### CODE REVIEW

**Comment by GanapathySanathBalaji** [comment]
Still have issues with the text ui test.

**Comment by terrytay** [comment]
> Still have issues with the text ui test.

i know how to fix that, it's a minor issue. We are not using Driver class anymore. Maybe you wanna rebase your latest build to the master?

**Comment by terrytay** [comment]
> > Still have issues with the text ui test.
> 
> i know how to fix that, it's a minor issue. We are not using Driver class anymore. Maybe you wanna rebase your latest build to the master?

u can either use git rebase or just pull the latest master and merge master to your branch-Parser before PR again

**Comment by GanapathySanathBalaji** [comment]
This is already merged with the latest master

**Comment by GanapathySanathBalaji** [comment]
The issue is rectified too

**Comment by GanapathySanathBalaji** [comment]
I have made a temporary fix but we need to change some segments of our code, I will do it later

**Pull request merged**
